<a href="https://colab.research.google.com/github/uddipan-pal/Computational-physics-/blob/main/assignment1_computational_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#q11 linalg solve
import numpy as np

# Set 1: Coefficient matrix A and constant vector b
A1 = np.array([[3, -1, 1],
               [3, 6, 2],
               [3, 3, 7]])
b1 = np.array([1, 0, 4])

# Set 2: Coefficient matrix A and constant vector b
A2 = np.array([[10, -1, 0],
               [-1, 10, -2],
               [0, -2, 10]])
b2 = np.array([9, 7, 6])

# Set 3: Coefficient matrix A and constant vector b
A3 = np.array([[10, 5, 0, 0],
               [5, 10, -4, 0],
               [0, -4, 8, -1],
               [0, 0, -1, 5]])
b3 = np.array([6, 25, -11, -11])

# Set 4: Coefficient matrix A and constant vector b
A4 = np.array([[4, 1, 1, 0, 1],
               [-1, -3, 1, 1, 0],
               [2, 1, 5, -1, -1],
               [-1, -1, -1, 4, 0],
               [0, 2, -1, 1, 4]])
b4 = np.array([6, 6, 6, 6, 6])

# Solve the systems of linear equations
x1 = np.linalg.solve(A1, b1)
x2 = np.linalg.solve(A2, b2)
x3 = np.linalg.solve(A3, b3)
x4 = np.linalg.solve(A4, b4)

# Print the solutions
print("Solution for set 1:")
print(x1)
print("\nSolution for set 2:")
print(x2)
print("\nSolution for set 3:")
print(x3)
print("\nSolution for set 4:")
print(x4)


Solution for set 1:
[ 0.03508772 -0.23684211  0.65789474]

Solution for set 2:
[0.99578947 0.95789474 0.79157895]

Solution for set 3:
[-0.79764706  2.79529412 -0.25882353 -2.25176471]

Solution for set 4:
[ 0.78663239 -1.00257069  1.86632391  1.9125964   1.98971722]


In [ ]:
#Q16: solving matrix equation

import numpy as np


A = np.array([[0.2, 0.1, 1, 1, 0],
              [0.1, 4, -1, 1, -1],
              [1, -1, 60, 0, -2],
              [1, 1, 0, 8, 4],
              [0, -1, -2, 4, 700]])

b = np.array([1, 2, 3, 4, 5])

#the solution vector x
X = np.array([7.859713071, 0.422926408, -0.073592239, -0.540643016, 0.010626163])

y=([0,0,0,0,0])#guess

def jacobi(A,b,X,x): #jacobi method
  x=y.copy()
  it=0
  n=len(A)
  for k in range(100):
    nor=np.linalg.norm(x-X)
    #print(nor)
    if(nor<0.01):#tolerance
      it=k+1  #iteration count
      break
    x_old=x.copy()
    for i in range(n):
      s=0.0
      for j in range(n):
        if(i!=j):
          s=s+A[i][j]*x_old[j]

      x[i]=(-s+b[i])/A[i][i]
  return x,it



def gs(A,b,X,x): #gs method
  x=y.copy()
  it=0
  n=len(A)
  for k in range(100):
    nor=np.linalg.norm(x-X)
    #print(nor)
    if(nor<0.01): #tolerance
      it=k+1  #iteration count
      break
    x_old=x.copy()
    for i in range(n):
      s1=0.0
      for j in range(n):
        if(j<i):
          s1=s1+A[i][j]*x[j] #kth iteration value
      s2=0.0
      for j in range(n):
        if(j>i):
          s2=s2+A[i][j]*x_old[j]   #k-1th iteration value

      x[i]=(-s1-s2+b[i])/A[i][i]
  return x,it


def relax(A,b,X,x,w): #relaxation method
  x=y.copy()
  it=0
  n=len(A)
  for k in range(100):
    nor=np.linalg.norm(x-X)
    if(nor<0.01): #tolerance
      it=k+1  #iteration count
      break
    x_old=x.copy()
    for i in range(n):
      s1=0.0
      for j in range(n):
        s1=s1+A[i][j]*x[j] #kth iteration value
      r=b[i]-s1 #residual vector component
      x[i]=x_old[i]+(w*r)/A[i][i]
  return x,it


def cg(A,b,X,x): #conjugate gradient method
  x=y.copy()
  it=0
  r=b-A @ x #residual vector
  v=r #search director
  #print(r)
  for k in range(100):
    nor=np.linalg.norm(x-X)
    if(nor<0.01): #tolerance
      it=k+1  #iteration count
      break
    t= (r.T @ r)/(v.T @ (A @ v))
    x=x+t*v
    r1=r-t*A @ v
    vn=(r1.T @ r1)/(r.T @ r)
    v=r1+vn*v
    r=r1
    #print(t,r,v)
  return x,it

#print("jacobi method:",jacobi(A,b,X,y))
#print("Gauss Seidel method:",gs(A,b,X,y))
print("Relaxation method with w=1.25",relax(A,b,X,y,1.25))
#print("Conjugate gradient method:",cg(A,b,X,y))


jacobi method: ([7.867984466554832, 0.42390690403119285, -0.07316380412616309, -0.5370925044467114, 0.01063184124837039], 40)
Gauss Seidel method: ([7.850914775668225, 0.4228013059532179, -0.07344797467914727, -0.539523257444223, 0.010619997694816878], 19)
Relaxation method with w=1.25 ([7.851527006791952, 0.4227737139591007, -0.07348302578382504, -0.5397836936250391, 0.010622858817903145], 8)
Conjugate gradient method: (array([ 7.85971308,  0.42292641, -0.07359224, -0.54064302,  0.01062616]), 6)


In [ ]:
#q1
import numpy as np
def pri(*args):
    for arg in args:
        print(arg)

# Example function to be decorated

A=np.array([[1,0.5],[0.5,0.33]])
b=np.array([0.24,0.13])

A = np.array([[0.1, 0.2], [0.2, 113]])
# Define the constant vector
b = np.array([0.3, 113.2])
y=np.array([0,0])
def cg(A,b,x): #conjugate gradient method
  ##b=np.round(b,2)
  x=y.copy()
  it=0
  r=b-A @ x #residual vector
  v=r #search director
  pri(r)
  print(r.T @ r)
  for k in range(3):
    print(v.T @ (A @ v))
    t= (r.T @ r)/(v.T @ (A @ v))

    x=x+t*v
    r1=r-t*A @ v
    vn=(r1.T @ r1)/(r.T @ r)
    v=r1+vn*v
    r=r1
    it=it+1
    pri(t,x,r,v)
  return x,it

import numpy as np


A = np.array([[0.2, 0.1, 1, 1, 0],
              [0.1, 4, -1, 1, -1],
              [1, -1, 60, 0, -2],
              [1, 1, 0, 8, 4],
              [0, -1, -2, 4, 700]])

b = np.array([1, 2, 3, 4, 5])

#the solution vector x
X = np.array([7.859713071, 0.422926408, -0.073592239, -0.540643016, 0.010626163])

y=([0,0,0,0,0])#guess

def jacobi(A,b,X,x): #jacobi method
  x=y.copy()
  it=0
  n=len(A)
  for k in range(100):
    nor=np.linalg.norm(x-X)
    #print(nor)
    if(nor<0.01):#tolerance
      it=k+1  #iteration count
      break
    x_old=x.copy()
    for i in range(n):
      s=0.0
      for j in range(n):
        if(i!=j):
          s=s+A[i][j]*x_old[j]

      x[i]=(-s+b[i])/A[i][i]
  return x,it



def gs(A,b,X,x): #gs method
  x=y.copy()
  it=0
  n=len(A)
  for k in range(100):
    nor=np.linalg.norm(x-X)
    #print(nor)
    if(nor<0.01): #tolerance
      it=k+1  #iteration count
      break
    x_old=x.copy()
    for i in range(n):
      s1=0.0
      for j in range(n):
        if(j<i):
          s1=s1+A[i][j]*x[j] #k-1th iteration value
      s2=0.0
      for j in range(n):
        if(j>i):
          s2=s2+A[i][j]*x_old[j]   #kth iteration value

      x[i]=(-s1-s2+b[i])/A[i][i]
  return x,it


def relax(A,b,x,w): #relaxation method
  x=y
  it=0
  n=len(A)
  for k in range(2):
    x_old=x.copy()
    for i in range(n):
      s1=0.0
      for j in range(n):
        s1=s1+A[i][j]*x[j] #kth iteration value
      r=b[i]-s1 #residual vector component
      x[i]=x_old[i]+(w*r)/A[i][i]
      pri(r)
    pri("r","x_k-1",x_old,"x_k",x)
  return x

A1 = np.array([[3, -1, 1],
               [3, 6, 2],
               [3, 3, 7]])
b1 = np.array([1, 0, 4])

# Set 2: Coefficient matrix A and constant vector b
A2 = np.array([[10, -1, 0],
               [-1, 10, -2],
               [0, -2, 10]])
b2 = np.array([9, 7, 6])

# Set 3: Coefficient matrix A and constant vector b
A3 = np.array([[10, 5, 0, 0],
               [5, 10, -4, 0],
               [0, -4, 8, -1],
               [0, 0, -1, 5]])
b3 = np.array([6, 25, -11, -11])

# Set 4: Coefficient matrix A and constant vector b
A4 = np.array([[4, 1, 1, 0, 1],
               [-1, -3, 1, 1, 0],
               [2, 1, 5, -1, -1],
               [-1, -1, -1, 4, 0],
               [0, 2, -1, 1, 4]])
b4 = np.array([6, 6, 6, 6, 6])

print("relaxation method:")
print(relax(A2,b2,[0,0,0],1.1) )

relaxation method:
9.0
7.99
7.7578000000000005
r
x_k-1
[0, 0, 0, 0, 0]
x_k
[0.99, 0.8789000000000001, 0.8533580000000001, 0, 0]
-0.021100000000000563
0.9053949999999986
-0.5765931000000002
r
x_k-1
[0.99, 0.8789000000000001, 0.8533580000000001, 0, 0]
x_k
[0.987679, 0.97849345, 0.789932759, 0, 0]
[0.987679, 0.97849345, 0.789932759, 0, 0]


In [ ]:
#q17 QR decomposition
import numpy as np
A=[[5,-2],[-2,8]]
#print(Q,R)
t=1.
A1=A
V=[[1,0],[0,1]]
while(np.abs(A1[0][1])>0.0001):
  Q,R=np.linalg.qr(A1)
  A1=np.dot(R,Q)
  V=np.dot(V,Q)
print("Eigenvalues produced after iterations within 0.0001 tolerance, using QR decomposition:",A1[0][0],A1[1][1])
print("Eigenvalues produced by \"eigh\" package:",np.linalg.eigh(A)[0] )

Eigenvalues produced after iterations within 0.0001 tolerance, using QR decomposition: 8.999999999456065 4.000000000543945
Eigenvalues produced by "eigh" package: [4. 9.]


In [ ]:
#q18 power method
from numpy import *
A=[[2,-1,0],[-1,2,-1],[0,-1,2]]
x=[[1],[0],[0]]
y=[[1],[0],[0]]
a=-100
temp=20
tol=20   #tolerance
q=np.zeros(len(x))
while(tol>0.01):
  q=x
  x=dot(A,x)
  temp=a   #to calc tol
  a=abs(dot(transpose(x),y)/dot(transpose(q),y)) #power method calc
  tol=(abs(a-temp)/a)
q=q/np.sqrt(q.T @ q)
print("upto 1% error Dominant eigenvalue :",a[0,0],"\n whose corresponding eigenvector :\n",q)
print("check for eigenvector:\n (1/l)A|x>=\n",A @ q /a)

upto 1% error Dominant eigenvalue : 3.3760539629005057 
 whose corresponding eigenvector :
 [[ 0.51376645]
 [-0.70697036]
 [ 0.48604212]]
check for eigenvector:
 (1/l)A|x>=
 [[ 0.51376645]
 [-0.7149617 ]
 [ 0.49734235]]


In [ ]:
#q19: singular value decomposition
import numpy as np
import time
m1 = np.array([[2,1],[1,0]])

m2 = np.array([[2,1],[1,0],[0,1]])

m3 = np.array([[2, 1],
                    [-1, 1]])

m4 = np.array([[1, 1, 0],
                    [-1, 0, 1],
                    [0, 1, -1]])

m5 = np.array([[1, 1, 0],
                    [-1, 0, 1],
                    [0, 1, -1]])

m6 = np.array([[0, 1, 1],
                    [0, 1, 0],
                    [1, 1, 0],
                    [0, 1, 0],
                    [1, 0, 1]])

def dia(m,S,n):
  S1=np.zeros((m,n))
  for i in range(m):
    for j in range(n):
      if(i==j):
        S1[i][j]=S[i]
  return S1
matrix=[m1,m2,m3,m4,m5,m6]

# Computing SVD for each matrix and measure time
for i in range(len(matrix)):

    print(f"\nComputing SVD for Matrix {i+1}...")
    start_time = time.time()
    U, S, VT = np.linalg.svd(matrix[i])
    end_time = time.time()
    print(f"Time taken: {end_time - start_time:.6f} seconds")

    print(f"\nSingular Value Decomposition for Matrix {i+1}:")
    print("U:")
    print(np.round(U,8))
    print("\nSingular Values (S):")
    print(dia(len(U),S,len(VT)))
    print("\nVT:")
    print(np.round(VT,8))
    # Reconstruct the original matrix
    reconstructed_matrix = U @ (dia(len(U),S,len(VT))) @ VT
    print("\nReconstructed Matrix:")
    print(np.round(reconstructed_matrix,8))
    # Check if original matrix and reconstructed matrix are equal within some tolerance
    print("\nOriginal and reconstructed matrix are equal within tolerance:",1e-6)
    print(np.allclose(matrix[i], reconstructed_matrix,atol=1e-6))